travis:
  secure:
    BINSTAR_TOKEN: asJ+dYWnJHeehsnwZos1yjFsAibSOEeY/YaQCGxqIxUM/Su7/qfqfFZEVPF/3CXByPh7XROsCQjxMMg/SvdNeHFkmt6SYIOkoXLCNzgIS6XE2LqOC1ikIjLwMDizU6IdGkl5eG1QqXWUVz7f2x5NySn2HQ54oiVNSaYYRYyuBItCYDV4iSwKZeb7Eq/P8B3Y7R9tMzCMyQdcVK7cYsOmxsjfY0eYRuHwqXfLBQ2DL0XYuvxxUM4mUb7BKWhOjZ4iULSWJ4d0Y2rRQ0natWgB5J9ScRHweYs6nDRo7fIuCmoJBHVx6OutDbQon9Q+5C++fZ/xZ3qZ1mnN8D1ACYbR20ROwmwC5xxPepPv1wFsPxHjT5nd18dMNBxNHJQVaTxbC9Ov5GoxxqjA28diR3LBR/NBIZ5QRCRFhDWAHKU99wRZwI1zqzbCvp9vrClRsjPDKCi7c4oV3tMNi8Dam8IsV0TL4dG/s/sPegKnUxS4glU9Zs8Kj8SsCIdb3Uh/yFOxnc6p7l86Y1VbI9rjoAl25m7Rn99lCYbIQm7NdlvFLkFkvG09UXLeCxYb6gM/edhhKcvvpzM6EWkpikWX5COKC3Wu1vHSmYU0aQJ0qsB4n/OC8gKVx/k6dK1GK1yagzWT+6A3a0kTRwU+lMBbCgPgxzme498YGjawWEG8b0QMej4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
