travis:
  secure:
    BINSTAR_TOKEN: u1QOlUf9pGwKv61/O3+7trUmH1xumfI7gSVJ0LVw4jYugHNGPoVujI2X0GTiagBrbIq0qIjFjBT7Pig8i/p7QxDL3i0RvSv2CILEmNXUTvX5bCn1ZI6L5KFgSLF9OhyBhAvAPsHF3OT40RyzkWp8W1x+NKw+8DLmrS+pyMB1rtms9TYeqVCpFDnWO91h+OpFvDPGbn6fxLqt7lwVaB5Ilgwm7QJ2qWds6znQgwhOv7XLe43RkJWeCBk1BwISOnKxiwWZNUDjhZFI4V8Rg79+CQPYAo+YSHoL+enRt+hziEQhrTGjMcGcvr/jE+GtqFJaY5TqXRHaYQrkmiSF3YJlf1gsKlrZt889HSK7dC7MK7dh5xTnqoTkD390GXecz5MbSTERMTz55KTvQPSxsbrZPbUQTXoRJayTmhhOqB3no/vcsub66Nx2hVgUhfM55w7F+FYvVlOYvpb9wXK3pU0UMwxNpWh/rovl/oGNXkWQgm++ErID/iN7pFEl5XDusojxovSsbgJYQ1IrHCwcQCMPvDTViB5vgpG7+aFnfSNR3LDvBzL6CbkmqubFrk0La9b+pJuYXEmPbj6pHOnq2Wy3sgSu6+VpxknG7mFI7GP/9wOae+cjGZxKUChL71ZDk8i6HT5AX9ltNdx+o+BCvsPwygj9Zcb4PdiTGD4Oet1ogXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
